# -*- coding: utf-8 -*-
"""Tao_QR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RsKzqSkkER23X4tucNiTw2xA5__5M4WY
"""

import streamlit as st
import pandas as pd

# === Cấu hình ===
SHEET_ID = "1K5EM2wWmKWs5_FSg6SBsUyD8UkGSMAhPnn5ED_VmUPE"
SHEET_NAME = "Sheet1"  # nếu sheet bạn tên khác thì sửa lại

# === Đọc dữ liệu từ Google Sheets ===
url = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/gviz/tq?tqx=out:csv&sheet={SHEET_NAME}"
df = pd.read_csv(url)

# === Thiết lập giao diện ===
st.set_page_config(page_title="Tra cứu tài sản", page_icon="📦", layout="centered")

st.title("📦 Tra cứu thông tin tài sản")

# Lấy tham số từ URL (so_the)
query_params = st.query_params  # không có ngoặc
so_the = query_params.get("so_the", [""])[0].strip()

# Nếu có mã số thẻ
if so_the:
    st.subheader(f"Mã số thẻ: {so_the}")
    # Chuẩn hóa dữ liệu để tránh lỗi khi có khoảng trắng hoặc số dạng B02.0
    df["Số thẻ"] = df["Số thẻ"].astype(str).str.strip().str.upper().str.replace(".0", "", regex=False)
    so_the = so_the.upper().strip()

    # Lọc đúng dòng
    ts = df[df["Số thẻ"] == so_the]

    if not ts.empty:
        record = ts.iloc[0]
        st.markdown(f"""
        **Tên tài sản:** {record['TÊN TÀI SẢN']}
        **Đơn vị tính:** {record['Đơn vị tính']}
        **Năm sử dụng:** {int(record['Năm sử dụng']) if not pd.isna(record['Năm sử dụng']) else 'N/A'}
        **Số lượng:** {int(record['Số lượng']) if not pd.isna(record['Số lượng']) else 'N/A'}
        **Nguyên giá:** {int(record['Nguyên giá']):,} VNĐ
        **Hao mòn:** {int(record['Hao mòn']):,} VNĐ
        **Giá trị còn lại:** {int(record['Giá trị còn lại']):,} VNĐ
        """)
    else:
        st.warning("⚠️ Không tìm thấy tài sản với mã số thẻ này.")
else:
    st.info("🔎 Hãy nhập mã số thẻ vào URL, ví dụ: `...?so_the=B02`")
